### PR TITLE
Fix parent locales

### PR DESCRIPTION
**Pull request by camertron**
Oops, I [borked](https://github.com/svenfuchs/ruby-cldr/pull/38#issuecomment-306159358) `thor cldr:export` with my parent locales branch. This should fix it.

attn @tigrish

### CODE REVIEW

**Comment by froyomuffin** [comment]
@tigrish Heyo, this is still an issue from the looks of it. Could we merge this if it's still valid? :)

**Comment by tigrish** [comment]
Hey @camertron is this still up to date?

**Comment by camertron** [comment]
@tigrish oof this is an old branch... not sure I even remember what this was trying to do. I'll look into it.

**Comment by froyomuffin** [comment]
I think this can be closed

**Comment by camertron** [comment]
@froyomuffin ah ok cool. Was this addressed in another branch?

**Comment by camertron** [comment]
Just confirmed this is still necessary, `thor cldr:export` errors out without it.

**Comment by froyomuffin** [comment]
Gah, sorry I missed the message T-T. Thanks for the fix. :)

**Pull request merged**
